name: Build and Publish OpenHAB Ryobi Add-on

on:
  push:
    branches:
      - ryobi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build OpenHAB Add-on
      run: |
        ./mvn clean install -pl :org;openhab.binding.ryobi

    - name: Upload JAR to GitHub Packages
      uses: actions/upload-artifact@v2
      with:
        name: openhab-addon
        path: bundles/org.openhab,binding.ryobi/**/*.jar

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload JAR to Release Assets
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bundles/org.openhab,binding.ryobi/**/*.jar
        asset_name: org.openhab.binding.ryobi-${{ github.sha }}.jar
        asset_content_type: application/java-archive
